### ISSUE TITLE
DB error 

### ISSUE THREAD

**Issue by Cyb3rGh0st786** [NotSoSecure/android_application_analyzer#4]
Hello Team,

While selecting any database I am getting the following error 

File "main.py", line 127, in GetAllTables
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
sqlite3.DatabaseError: database disk image is malformed
Abort trap: 6

**Comment by devsecboy** [comment]
In my opinion, your database is corrupted.
Can you please try to open the database inside /android_application_analyzer/db directory with sqlite3 command-line utility.

**Comment by realsanjay** [comment]
Closing the issue due to inactivity if the issue still persist, please feel free to open a new issue

**Comment by realsanjay** [comment]
Closing the issue due to inactivity if the issue still persist, please feel free to open a new issue

**Comment by devsecboy** [comment]
Closing the issue due to inactivity if the issue still persists, please feel free to open a new issue
