### ISSUE TITLE
Issue while running program in window,ImportError: DLL load failed: PyQt5 

### ISSUE THREAD

**Issue by m4xx101** [NotSoSecure/android_application_analyzer#6]
While running this tool in windows I'm getting following error tried multiple Blogs on the Internet but nothing resolves this, any idea on the following?

```sh
C:\Users\android_application_analyzer>python3 main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from gui import *
  File "C:\Users\android_application_analyzer\gui.py", line 2, in <module>
    from PyQt5 import QtCore, QtWidgets, QtGui
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by devsecboy** [comment]
@m4xx101
Acknowledge: Working on the issue

**Comment by devsecboy** [comment]
@m4xx101

I have tested this issue and looks like issue is related to python configuration on Windows OS.

Reference: https://stackoverflow.com/questions/42863505/dll-load-failed-when-importing-pyqt5

By installing the stable release of python "Python 3.9.0 - Oct. 5, 2020", the issue get resolved

Please check and let us know about further query/issue

**Comment by devsecboy** [comment]
Closing the issue due to inactivity if the issue still persists, please feel free to open a new issue
